### ISSUE TITLE
Los carácteres especiales no se ven bien en Windows

### ISSUE THREAD

**Issue by jorgesumle** [jorgesumle/Octogonave#9]
Parece que hay algún problema con la codificación que hace que los carácteres especiales no se vean bien. Esto solo ocurre en Windows.

**Comment by antoiba86** [comment]
Lo he solucionado.

Tienes que añadir esto al código que lee el fichero.

try {
            br = new BufferedReader(new InputStreamReader(in, "UTF-8"));
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(LanguageFileReader.class.getName()).log(Level.SEVERE, null, ex);
        }

**Comment by jorgesumle** [comment]
Gracias, la próxoma vez haz un Pull Request ;)
